import json
import unittest

from scripts.measure_v16_rc5_r5a_recovery import FIXTURE, OUTPUT, SOURCE, targeted_firing, validate
from scripts.package_v16_rc5_r5a_recovery import build


class R5ARecoveryTest(unittest.TestCase):
    def test_provenance_and_split(self):
        self.assertTrue(all(validate(json.loads(FIXTURE.read_text()), json.loads(SOURCE.read_text())).values()))

    def test_recovery_state_machine_fires(self):
        import tempfile
        from pathlib import Path
        with tempfile.TemporaryDirectory() as directory:
            candidate = Path(directory) / "agent.py"
            build(candidate)
            row = targeted_firing(candidate, [{"seed": 1, "seat": 0}])[0]
        self.assertTrue(row["fired"])
        self.assertEqual({"align": 1, "place": 1, "resume": 1}, row["telemetry"])

    def test_measurement_contract(self):
        if not OUTPUT.exists():
            self.skipTest("measurement is generated by the dedicated evaluator")
        report = json.loads(OUTPUT.read_text())
        self.assertTrue(report["passed"])
        self.assertEqual("NOT_PERFORMED", report["kaggle_submission"])
        self.assertEqual("PASS", report["runtime_contract"])


if __name__ == "__main__":
    unittest.main()
